export { default as authRouter } from './auth/auth.route';
export { default as coordinatorRouter } from './coordinator/coordinator.route';
export { default as applicantRouter } from './coordinator/applicant.route';
export { default as announcementRouter } from './coordinator/announcement.route'
export { default as userRouter } from './profile/profile.route';
export { default as uploadRouter } from './file_management/upload.route'
export { default as generalTaskRouter } from './tasks'
export { default as pingRouter } from './server/ping'
export { default as extraRouter } from './extra.route'
export { default as leaderBoardRouter } from './leaderboard.route'
export { default as groupRouter } from './groups/group.route'
export { default as mentorsRouter } from './mentorship.route'
export { default as meetingRouter } from './meeting.route'
export { default as meetingAttendanceRouter } from './meeting_attendance.route'
export { default as zoomWebhookRouter } from './zoom_webhook.route'